--------------------------------------------------------
--  File created - Wednesday-August-24-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERSB
--------------------------------------------------------

  CREATE TABLE "ROOT"."USERSB" 
   (	"USER_ID" NUMBER(*,0) DEFAULT 110, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(20 BYTE), 
	"AGE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"BLOODGROUP" VARCHAR2(20 BYTE), 
	"ELIGIBILITY" VARCHAR2(20 BYTE), 
	"LASTBLOOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ROOT.USERSB
SET DEFINE OFF;
Insert into ROOT.USERSB (USER_ID,USERNAME,PASSWORD,ROLE,AGE,EMAIL,PHONE,BLOODGROUP,ELIGIBILITY,LASTBLOOD) values (110,'Rakibul','1234567','Donor','24','rakibul@gmail.com','01708119668','AB+','YES','2022-08-24');
Insert into ROOT.USERSB (USER_ID,USERNAME,PASSWORD,ROLE,AGE,EMAIL,PHONE,BLOODGROUP,ELIGIBILITY,LASTBLOOD) values (101,'DEBORAJ','12345','Donor','22','deboraj@email.com','01708119559','O+','YES',null);
Insert into ROOT.USERSB (USER_ID,USERNAME,PASSWORD,ROLE,AGE,EMAIL,PHONE,BLOODGROUP,ELIGIBILITY,LASTBLOOD) values (102,'ABUR RAHMAN','09876','Patient','23','abdur@email.com','01709119449','A+','YES',null);
Insert into ROOT.USERSB (USER_ID,USERNAME,PASSWORD,ROLE,AGE,EMAIL,PHONE,BLOODGROUP,ELIGIBILITY,LASTBLOOD) values (110,'ABUR_RAHMAN2','ABUR_RAHMAN2','Donor','ABUR_RAHMAN2','ABUR_RAHMAN2','ABUR_RAHMAN2','A+','YES',null);
Insert into ROOT.USERSB (USER_ID,USERNAME,PASSWORD,ROLE,AGE,EMAIL,PHONE,BLOODGROUP,ELIGIBILITY,LASTBLOOD) values (110,'Tutul','13579','Patient','25','tutul@gmail.com','01809875322','O+','NO','2022-08-24');
Insert into ROOT.USERSB (USER_ID,USERNAME,PASSWORD,ROLE,AGE,EMAIL,PHONE,BLOODGROUP,ELIGIBILITY,LASTBLOOD) values (110,'Goutom','1234567','Donor','24','goutom@gmail.com','01301709193','AB+','NO','2022-08-24');
Insert into ROOT.USERSB (USER_ID,USERNAME,PASSWORD,ROLE,AGE,EMAIL,PHONE,BLOODGROUP,ELIGIBILITY,LASTBLOOD) values (110,'Binty','Binty','Donor','22','Binty@email.com','09876543456789','A+','YES',null);
Insert into ROOT.USERSB (USER_ID,USERNAME,PASSWORD,ROLE,AGE,EMAIL,PHONE,BLOODGROUP,ELIGIBILITY,LASTBLOOD) values (110,'Faruk','Faruk','Donor','24','faruk@emailcom','01937383233','B+','NO','2022-08-24');
--------------------------------------------------------
--  DDL for Index USERSB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."USERSB_PK" ON "ROOT"."USERSB" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERSB
--------------------------------------------------------

  ALTER TABLE "ROOT"."USERSB" MODIFY ("BLOODGROUP" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."USERSB" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."USERSB" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."USERSB" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."USERSB" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."USERSB" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."USERSB" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."USERSB" ADD CONSTRAINT "USERSB_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
